import crypto from 'node:crypto';

/**
 * Stable hash used to de-duplicate leads across scrape runs.
 * Two posts with the same platform + url (or platform + title) collapse to one.
 *
 * Row ids themselves are generated by Postgres (`gen_random_uuid()`), so this
 * is the only identifier the application still computes.
 */
export function sourceHash(platform: string, url: string | null | undefined, title: string): string {
  const key = `${platform}::${(url && url.trim()) || title.trim().toLowerCase()}`;
  return crypto.createHash('sha1').update(key).digest('hex');
}
